# Generated by Django 5.0.1 on 2024-02-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_category_news_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='url',
            field=models.SlugField(default=1, max_length=160),
            preserve_default=False,
        ),
    ]
