# Generated by Django 5.0.1 on 2024-02-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_news_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.SlugField(max_length=160, unique=True),
        ),
    ]
