# Generated by Django 5.0.1 on 2024-01-23 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='userautomodel',
            name='auto',
        ),
        migrations.RemoveField(
            model_name='modelautomodel',
            name='brand',
        ),
        migrations.RenameModel(
            old_name='BrandAutoModel',
            new_name='BrandAuto',
        ),
        migrations.CreateModel(
            name='ModelAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.brandauto')),
            ],
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin_number', models.CharField(max_length=255)),
                ('status_rent', models.BooleanField(default=False)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.modelauto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.userauto')),
            ],
        ),
        migrations.DeleteModel(
            name='AutoModel',
        ),
        migrations.DeleteModel(
            name='UserAutoModel',
        ),
        migrations.DeleteModel(
            name='ModelAutoModel',
        ),
    ]
