# Generated by Django 5.0.1 on 2024-02-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='mileage',
            field=models.IntegerField(default=20000),
            preserve_default=False,
        ),
    ]
