# Generated by Django 5.0.1 on 2024-01-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlsn24',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
